__version__: str

class ClipboardError(RuntimeError): ...

def copy(data: None | str | tuple[int, int, bytes] | list[str], /) -> None: ...
def paste() -> str | dict[str, object] | list[str]: ...
def clear() -> None: ...
