__version__: str

class ClipboardError(RuntimeError): ...

def copy(data: object, /) -> None: ...
def copy_image(width: int, height: int, rgba_bytes: bytes, /) -> None: ...
def copy_files(paths: list[str] | list[os.PathLike[str]], /) -> None: ...
def paste() -> str | dict[str, object]: ...
def clear() -> None: ...
